//this is not in the build so not used probably
#pragma once

#define GATEWAY_MAX_SENSORS              10
#define GATEWAY_MAX_SENSOR_TYPES          4
#define GATEWAY_MAX_FRAME_PAYLOAD       244
#define GATEWAY_MAX_ADDRESS_LEN          18
#define GATEWAY_MAX_REQUEST_ID_LEN       64
#define GATEWAY_MAX_UUID_LEN             40
#define GATEWAY_MAX_SERVICE_UUIDS         8
#define GATEWAY_MAX_SENSOR_KEY_LEN       64
#define GATEWAY_MAX_SENSOR_NAME_LEN      32

#define GATEWAY_DEFAULT_SCAN_TIMEOUT_MS 30000
#define GATEWAY_DEFAULT_CONNECT_TIMEOUT_MS 15000
#define GATEWAY_DEFAULT_CONFIG_TIMEOUT_MS 10000
#define GATEWAY_DEFAULT_STREAM_RATE_HZ    60

#define GATEWAY_HEALTH_WINDOW_MS        3000
#define GATEWAY_MIN_HEALTH_RATE_HZ        58

#define GATEWAY_USE_JSON_PROTOCOL          1
#define GATEWAY_ENABLE_RAW_FRAME_FORWARD   1
#define GATEWAY_ENABLE_GATEWAY_TIMESTAMPS  1
